package com.spms.backend.model.notification;

public enum NotificationType {
    MEMBERSHIP_INVITE,
    ADVISOR_REQUEST,
    ADVISOR_DECISION,
    SYSTEM_ALERT,
    GROUP_DISBANDED,
    COMMITTEE_ASSIGNED
    MEMBERSHIP_INVITE, ADVISOR_REQUEST, ADVISOR_DECISION, SYSTEM_ALERT, GROUP_DISBANDED,
    ADVISOR_ASSIGNMENT, JURY_ASSIGNMENT, GROUP_ASSIGNMENT, SCHEDULE_CHANGE, MEETING_REMINDER, GENERAL
}
