package com.spms.backend.model;

public enum ActionType {
    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DISBANDED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    ADVISOR_ASSIGNED,
    ADVISOR_REQUESTED,
    ADVISOR_REQUEST_CANCELLED,
    ADVISOR_REQUEST_WITHDRAWN,
    ADVISOR_APPROVED,
    ADVISOR_REJECTED,
    ADVISOR_RELEASED,
    INTEGRATION_BOUND,
    INTEGRATION_REMOVED,
    ADVISOR_OVERRIDDEN,
    ADVISOR_RELEASED
}
