package com.spms.backend.model;

public enum ActionType {
    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DISBANDED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    ADVISOR_ASSIGNED,
    ADVISOR_REQUESTED,
    ADVISOR_APPROVED,
    ADVISOR_REJECTED,
    INTEGRATION_BOUND,
    INTEGRATION_REMOVED
}
