package com.spms.backend.model;

public enum ActionType {
    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DISBANDED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    ADVISOR_ASSIGNED,
    ADVISOR_REQUESTED,
    ADVISOR_REQUEST_CANCELLED,
    ADVISOR_REQUEST_WITHDRAWN,
    ADVISOR_APPROVED,
    ADVISOR_REJECTED,
    ADVISOR_RELEASED,
    INTEGRATION_BOUND,
    INTEGRATION_REMOVED,
    ADVISOR_OVERRIDDEN,
    COMMITTEE_GROUP_ASSIGNED,
    COMMITTEE_GROUP_STATUS_UPDATED,
    COMMITTEE_GROUP_REMOVED,
    COMMITTEE_CREATED,
    COMMITTEE_UPDATED,
    COMMITTEE_DELETED,
    JURY_ASSIGNED,
    SCHEDULE_CONFLICT_DETECTED
}
