spring:
  config:
    import: "optional:file:./backend/application.properties, optional:file:./application.properties"
  application:
    name: spms-backend
  datasource:
    url: ${db.url}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

server:
  port: 8080

github:
  client-id: ${Ov23liBp0P26wwpCX9xr}
  client-secret: ${2668412ff76aedad5d1d77626b7968c401cca7c7}
  redirect-uri: ${http://localhost:3000/auth/callback}

token:
  secret: ${eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNzgiLCJ1c2VySWQiOjE3OCwic3R1ZGVudElkIjoiNjU0MzIxIiwiZ2l0aHViVXNlcm5hbWUiOiJEaWxhcmFLdXlhciIsInJvbGUiOiJzdHVkZW50IiwicmVxdWlyZXNQYXNzd29yZENoYW5nZSI6ZmFsc2UsImlhdCI6MTc3NjQxNzQ1MywiZXhwIjoxNzc2NDIxMDUzfQ.W7DSZRQtU1wKspGGwwY0za1bKTOa1S1LxPWNCAjXsWc}
  expiration-seconds: ${TOKEN_EXPIRATION_SECONDS:3600}


