DB_URL=jdbc:postgresql://aws-1-eu-west-2.pooler.supabase.com:5432/postgres?user=postgres.coxnjbyfnqfcyhxuduwg&password=befwe4-Qamwik-werrom

GITHUB_CLIENT_ID=Ov23liBp0P26wwpCX9xr
GITHUB_CLIENT_SECRET=2668412ff76aedad5d1d77626b7968c401cca7c7
GITHUB_REDIRECT_URI=http://localhost:3000/auth/callback

TOKEN_SECRET=local-dev-secret-change-me-in-production
TOKEN_EXPIRATION_SECONDS=3600
