import { Group } from "@/lib/group-types";

export const mockGroups: Group[] = [
    {
        groupId: 101,
        groupName: "Alpha Team",
        status: "advised",
        leaderId: 1,
        leaderName: "Miray Yıldırım",
        advisorId: 11,
        advisorName: "Dr. Ayşe Yılmaz",
        memberCount: 4,
        githubBound: true,
        jiraBound: true,
        createdAt: "2026-04-01T10:00:00Z",
        updatedAt: "2026-04-08T14:30:00Z",
        members: [
            {
                userId: 1,
                studentId: "2201001",
                fullName: "Miray Yıldırım",
                role: "leader",
                githubUsername: "mirayy",
            },
            {
                userId: 2,
                studentId: "2201002",
                fullName: "Ayşe Demir",
                role: "student",
                githubUsername: "aysedemir",
            },
            {
                userId: 3,
                studentId: "2201003",
                fullName: "Mehmet Can",
                role: "student",
                githubUsername: "mehmetcan",
            },
            {
                userId: 4,
                studentId: "2201004",
                fullName: "Zeynep Su",
                role: "student",
                githubUsername: "zeynepsu",
            },
        ],
    },
    {
        groupId: 102,
        groupName: "Beta Builders",
        status: "forming",
        leaderId: 5,
        leaderName: "Ali Vural",
        advisorId: null,
        advisorName: null,
        memberCount: 3,
        githubBound: false,
        jiraBound: true,
        createdAt: "2026-04-02T09:15:00Z",
        updatedAt: "2026-04-07T11:00:00Z",
        members: [
            {
                userId: 5,
                studentId: "2201010",
                fullName: "Ali Vural",
                role: "leader",
                githubUsername: "alivural",
            },
            {
                userId: 6,
                studentId: "2201011",
                fullName: "Ece Aydın",
                role: "student",
                githubUsername: "eceaydin",
            },
            {
                userId: 7,
                studentId: "2201012",
                fullName: "Deniz Ak",
                role: "student",
                githubUsername: "denizak",
            },
        ],
    },
    {
        groupId: 103,
        groupName: "Code Crafters",
        status: "formed",
        leaderId: 8,
        leaderName: "Selin Aras",
        advisorId: 12,
        advisorName: "Dr. Mehmet Kaya",
        memberCount: 5,
        githubBound: true,
        jiraBound: false,
        createdAt: "2026-03-28T08:00:00Z",
        updatedAt: "2026-04-07T16:45:00Z",
        members: [
            {
                userId: 8,
                studentId: "2201020",
                fullName: "Selin Aras",
                role: "leader",
                githubUsername: "selinaras",
            },
            {
                userId: 9,
                studentId: "2201021",
                fullName: "Berk Tunç",
                role: "student",
                githubUsername: "berktunc",
            },
            {
                userId: 10,
                studentId: "2201022",
                fullName: "Cem Öztürk",
                role: "student",
                githubUsername: "cemozturk",
            },
            {
                userId: 13,
                studentId: "2201023",
                fullName: "Dila Kara",
                role: "student",
                githubUsername: "dilakara",
            },
            {
                userId: 14,
                studentId: "2201024",
                fullName: "Mina Koç",
                role: "student",
                githubUsername: "minakoc",
            },
        ],
    },
    {
        groupId: 104,
        groupName: "Delta Vision",
        status: "disbanded",
        leaderId: 15,
        leaderName: "Onur Işık",
        advisorId: null,
        advisorName: null,
        memberCount: 2,
        githubBound: false,
        jiraBound: false,
        createdAt: "2026-03-20T12:00:00Z",
        updatedAt: "2026-04-05T13:20:00Z",
        members: [
            {
                userId: 15,
                studentId: "2201030",
                fullName: "Onur Işık",
                role: "leader",
                githubUsername: "onurisik",
            },
            {
                userId: 16,
                studentId: "2201031",
                fullName: "Ela Güneş",
                role: "student",
                githubUsername: "elagunes",
            },
        ],
    },
];